Working branch
Nastiona-Slastiona/Responsive_Web_Page pull request #1
Opened 2021-11-10 08:50 UTC by Nastiona-Slastiona

2021-11-17 08:17 UTC, AndrewGulidov requested changes
In general result looks pretty well. Even cool.
Don't worry about a lot of comments. It is a normal situation for beginners. I am sure you will solve all the issues.

Note about the mobile version. If a resize the browser to the minimum height - the devices section is too large and I see a white block at the bottom of the page.

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/infobox.css
> +        position: relative;
Do you exactly need relative position?

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/infobox.css
> +button {
Let's discuss for what you use this style

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/infobox.css
> +input {
Should be concrete class with correct BEM name.
The same for form.

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/infobox.css
> +form {
In general, about using form in the project. Don't think you need it. But good that you tried to use it.

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/intro.css
> +        display: grid;
Not sure that you need grids for intro

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/intro.css
> +.intro__text span {
try to avoid this

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/intro.css
> +        top: -25%;
Is it correct?

2021-11-17 08:17 UTC, AndrewGulidov commented on assets/css/midbar.css
> +        left: 0vw;
if you use 0 you don't need to add vw, or px, or %, or anything

2021-11-17 08:34 UTC, Nastiona-Slastiona commented on assets/css/fonts.css
> +@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');
Yes, it gives me "Open Sans" font.

2021-11-17 11:54 UTC, AndrewGulidov commented on index.html
> +    <div class="wrapper">
<body>
<header>
<main>
<footer>
</body>

2021-11-17 11:56 UTC, AndrewGulidov commented on index.html
> +        <div class="rightButton"></div>
next, previous

2021-11-17 12:02 UTC, AndrewGulidov commented on index.html
> +                    <div class="message message--visible2 message__text ">Daily Mobile UI Design Inspiration #1<br>via @cssauthor</div>
--opacity-max

2021-11-28 15:28 UTC, AndrewGulidov commented on styles/css/adertisement-section/item/advertisement-section__items.css
> +.advertisement-section__item {
These styles should live in `advertisement.css`. Do not separate it and do not create subfolders.

2021-11-28 15:28 UTC, AndrewGulidov commented on styles/css/adertisement-section/advertisement-section.css
> +@media (min-width: 1020px) {
Please add empty rows between classes, media queries and etc.

2021-11-28 15:30 UTC, AndrewGulidov commented on index.html
> +    <section class="banner">
You didn't updates structure to
`header`
`main`
`footer`

2021-11-28 15:36 UTC, AndrewGulidov commented on index.html
> +                                        <img class="menu__item-icon"  src="./styles/icons/aboutus.svg" alt="About us"></img>
Did you tried to find icons instead of exporting them from photoshop?

2021-11-28 15:36 UTC, AndrewGulidov commented on index.html
> +                            <div class="intro">
extra spaces in indent

2021-11-28 15:37 UTC, AndrewGulidov commented on index.html
> +                                    <div class="primary">The cool</div>
Classes should be named like `intro__primary-text`

2021-11-28 15:41 UTC, AndrewGulidov commented on index.html
> +                    <header class="header">
Why the header is inside banner? It should be the first section.

2021-11-28 15:44 UTC, AndrewGulidov commented on assets/css/header.css
> +    .header .logo {
Didn't I mention that you don't need to use such separators? And it should be a modifier or something else in logo class?

2021-11-28 15:45 UTC, AndrewGulidov commented on assets/css/header.css
> +    header .logo__text {
Didn't fix that? Don't use tags inside css.

2021-11-28 15:47 UTC, AndrewGulidov commented on styles/css/common_elements/play-button--rounded.css
> +  background-image: url('../../../static/images/play.png');
Did you forget to replace it with SVG inside markup?

2021-11-28 15:48 UTC, AndrewGulidov commented on styles/css/common_elements/player.css
> +    background-image: url('../../../static/images/play.png');
Did you forget to replace it with SVG inside markup?
Please check other places with background-image.

2021-11-28 15:49 UTC, AndrewGulidov commented on styles/css/common_elements/player.css
> +  .player__button-play {
player__play-button would be better

2021-11-28 15:49 UTC, AndrewGulidov commented on styles/css/common_elements/player.css
> +  .player__sound {
player__volume-button

2021-12-05 11:25 UTC, AndrewGulidov commented on styles/css/adertisement/advertisement.css
> +.advertisement-section {
It seems that now you don't need subfolders. because they contains only one file.
I think that common_elements also doesn't make sense. Just put all *.css files under 'css' folder.

2021-12-05 11:26 UTC, AndrewGulidov commented on styles/css/devices/devices.css
> +.sticker__text {
everything that doesn't start with `.devices` shoul be placed in a separate files. Please check other files. Possibly in some places you have the same issue.

2021-12-05 11:26 UTC, AndrewGulidov approved these changes

2021-12-06 14:10 UTC, merged